### ISSUE TITLE
Ещё есть, что подправить :)

### ISSUE THREAD

**Issue by Pyromanc3r** [EugVV/DivOS-EE-ru#20]
Недавно закончил проходить переиздание этой замечательной игры и частенько попадались всякие ошибки и опечатки. Возможно, что в некоторых моментах это вовсе не ошибки, а просто сложные предложения со специфическим письмом. В общем, посмотрите, вот:
![20211009164139_1](https://user-images.githubusercontent.com/17619385/151667285-58441360-3f03-4b1b-af09-90e55ca4f918.jpg)
![20211016003142_1](https://user-images.githubusercontent.com/17619385/151667289-bc8f3c0d-90c5-44ba-9cff-7bfc30b2b48f.jpg)
![20211029041809_1](https://user-images.githubusercontent.com/17619385/151667290-903dd56a-eafe-41c9-a294-d8bd160ebe68.jpg)
![20211029043111_1](https://user-images.githubusercontent.com/17619385/151667291-72c3533f-160d-494a-b573-2f20007716c7.jpg)
![20211103060121_1](https://user-images.githubusercontent.com/17619385/151667292-73bc0c18-bf1d-40e7-a744-8b2b7ac10313.jpg)
![20211105032704_1](https://user-images.githubusercontent.com/17619385/151667293-8a15b456-28d7-45e3-9312-ba8bccf4b80b.jpg)
![20211107021323_1](https://user-images.githubusercontent.com/17619385/151667295-277a77b8-0c2e-44e0-b79b-70eee6767cad.jpg)
![20211107204050_1](https://user-images.githubusercontent.com/17619385/151667299-3d5930fe-0e9b-4496-9a6c-3caed18afbde.jpg)
![20211108033658_1](https://user-images.githubusercontent.com/17619385/151667301-53677c93-4069-4879-ac60-6b5600fbb82d.jpg)
![20211108044144_1](https://user-images.githubusercontent.com/17619385/151667302-99f3f9f7-f5f5-4685-9b4c-718224ffbfb0.jpg)
![20211108045242_1](https://user-images.githubusercontent.com/17619385/151667303-03c58d73-0cb2-4006-a9be-ce883a841ca5.jpg)
![20211120205956_1](https://user-images.githubusercontent.com/17619385/151667305-486e94d7-ecba-47fa-aaba-3ad14c241422.jpg)
![20211121161607_1](https://user-images.githubusercontent.com/17619385/151667307-65bff7a2-3f6e-4c13-8ba8-43f80f0a9110.jpg)
![20211121161734_1](https://user-images.githubusercontent.com/17619385/151667309-001a587a-3169-4c15-b186-faf04ff0908d.jpg)
![20211121172927_1](https://user-images.githubusercontent.com/17619385/151667311-d6195823-11c6-487f-9a58-106978ab3cd3.jpg)
![20220102210747_1](https://user-images.githubusercontent.com/17619385/151667312-9f1815aa-5749-410f-a42e-151cac019fc3.jpg)
![20220104204757_1](https://user-images.githubusercontent.com/17619385/151667313-4aadac69-f8a0-4723-a75c-376e6789ae65.jpg)
![20220127094844_1](https://user-images.githubusercontent.com/17619385/151667314-d83f69e6-343f-48ad-958a-5055170e74d6.jpg)
![20220127102724_1](https://user-images.githubusercontent.com/17619385/151667315-6d03dd49-f545-4305-aa1c-66b1c3779238.jpg)
![20220128061331_1](https://user-images.githubusercontent.com/17619385/151667316-211b7eda-f8a6-484e-ab8a-154a8de1fa32.jpg)
![20220128084818_1](https://user-images.githubusercontent.com/17619385/151667319-53f82178-36c8-46d5-a258-118a5a7756eb.jpg)
![20220128084823_1](https://user-images.githubusercontent.com/17619385/151667321-ee80d9e2-de5e-49d0-ae76-ec58e46c481f.jpg)

**Comment by EugVV** [comment]
Спасибо, исправил, что возможно. Но не всё из этого является ошибкой:«разражается», «сонм», некоторые другие устаревшие/книжные/просторечные выражения вполне к месту, на мой взгляд. Что касается английской реплики, я не нашёл её ни в русском, ни в английском тексте, ни даже в файлах с логикой диалогов. Не могу ни прокомментировать, ни исправить.
